### ISSUE TITLE
Crear un mecanismo de guardado en almacenamiento persistente

### ISSUE THREAD

**Issue by Pires95** [Guiamrey/Battleship_Android#14]
Para que el algoritmo pueda aprender de forma persistente, es necesario encontrar la forma de almacenar en memoria no volátil todos los datos necesarios para mantener los parámetros aprendidos.

**Comment by jacoboqc** [comment]
Ahora mismo se emplean preferencias compartidas para el almacenamiento de la matriz del usuario y su acceso desde varias Activities, pero Android provee de más mecanismos de persistencia. Echar un ojo a https://developer.android.com/guide/topics/data/data-storage.html
Caché o base de datos, hay varias opciones.
