### ISSUE TITLE
Implementar niveles de dificultad de juego

### ISSUE THREAD

**Issue by Guiamrey** [Guiamrey/Battleship_Android#23]
@Pires95 y yo estuvimos hablando y pensamos que se podría hacer de esta forma. A ver que pensáis @likytho @jacoboqc .
Todo lo que se pone concierne a la IA.
      **- Fácil**:  disparos aleatorios (aún cuando toca barco) y colocación de barcos aleatoria.
      **- Medio:** disparos aleatorios pero que siga con el barco si ha tocado uno y colocación de barcos aleatoria.
      **- Difícil:** disparos y colocación de barcos inteligentes.

**Comment by jacoboqc** [comment]
Me parece bien, es una forma de hacerlo sin complicarse mucho la existencia.

**Comment by likytho** [comment]
Entonces, como quien dice, fácil y medio están hechos prácticamente... Quizá disparos aleatorios no del todo, lo compruebo a ver...

**Comment by Guiamrey** [comment]
Solo queda que @likytho ponga la colocación de barcos inteligente.
