### ISSUE TITLE
Actualizar código de detectar colocación de barcos correcta con la ultima versión de isAShip o como se llame 

### ISSUE THREAD

**Issue by Pires95** [Guiamrey/Battleship_Android#28]

**Comment by likytho** [comment]
Que yo sepa, esto ya está correcto. Que lo confirme @Guiamrey por si las moscas.

Y con respecto al bug que me dijiste por Telegram, no hay tal bug, lo más probable es que la variable ALLOW_ADJACENT_SHIPS no estuviera bien puesta (o no se haya cambiado, o cualquier cosa...)

Por defecto está a false, es decir, por defecto no se permiten barcos juntos (se declara a false, se puede cambiar...)
