### ISSUE TITLE
Marcar barcos hundidos tanto del jugador como de la maquina

### ISSUE THREAD

**Issue by Guiamrey** [Guiamrey/Battleship_Android#7]
Cuando un barco se haya hundido marcarlo en la tabla (las dos, jugador y maquina) de forma diferente a si solo se ha tocado, para distinguir barcos hundidos y no.
Se pueden poner unas imagenes debajo de la tabla de juego donde el jugador dispara con los barcos hundidos y por hundir.

**Comment by Guiamrey** [comment]
Realmente no se cómo hacer esto, lo de las imágenes es algo inviable a menos que se junten más las matrices y aún así quedaría un espacio bastante pequeño. Adjunto una captura en un Nexus 5 para que se pueda ver.
![nexus5_game](https://cloud.githubusercontent.com/assets/12219453/21965326/0d5618b2-db5e-11e6-9877-8792a96e4fb1.jpg)

**Comment by Pires95** [comment]
La opcion mas sencilla que se me ocurrio para esto, fue darle hacia abajo a la matrix de abajo, borrar los botonesde interrogacion y pausa que a dia de hoy no hacen nada, poner el semaforo mas bajo, y meter los 5 barcos ahi y los hundidos marcarlos en gris, tal cual se hace en la pantalla de colocar barcos.

En ese hueco a la izquierda es el unico donde veo que pueden entrar los barcos
